<?php

/**
 * August Ash Backend Module
 *
 * @author   Josh Johnson <josh@augustash.com>
 * @copyright Copyright (c) 2020 August Ash (https://www.augustash.com)
 */

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Augustash\Backend\ViewModel\SiteVerification $viewModel */
$viewModel = $block->getSiteVerificationViewModel();

$scope = \Magento\Store\Model\ScopeInterface::SCOPE_STORES;
$scopeCode = $viewModel->getStoreCode();

$googleVerification = $viewModel->getGoogleSiteVerification($scope, $scopeCode);
$bingVerification = $viewModel->getBingSiteVerification($scope, $scopeCode);

?>

<?php if (!empty(trim($googleVerification))): ?>
<!-- BEGIN GOOGLE SITE VERIFICATION -->
<meta name="google-site-verification" content="<?= trim($googleVerification); ?>" />
<!-- END GOOGLE SITE VERIFICATION -->
<?php endif; ?>

<?php if (!empty(trim($bingVerification))): ?>
<!-- BEGIN BING SITE VERIFICATION -->
<meta name="msvalidate.01" content="<?= trim($bingVerification); ?>" />
<!-- END BING SITE VERIFICATION -->
<?php endif; ?>