<?php

/**
 * August Ash Backend Module
 *
 * @author    Josh Johnson <jjohnson@augustash.com>
 * @copyright 2023 August Ash, Inc. (https://www.augustash.com)
 */

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Augustash\Backend\ViewModel\SiteVerification $viewModel */
$viewModel = $block->getSiteVerificationViewModel();
?>
<?php if ($viewModel->getGoogleSiteVerification() !== null): ?>
<!-- BEGIN GOOGLE SITE VERIFICATION -->
<meta name="google-site-verification" content="<?= $escaper->escapeHtml($viewModel->getGoogleSiteVerification()) ?>" />
<!-- END GOOGLE SITE VERIFICATION -->
<?php endif; ?>
<?php if ($viewModel->getBingSiteVerification() !== null): ?>
<!-- BEGIN BING SITE VERIFICATION -->
<meta name="msvalidate.01" content="<?= $escaper->escapeHtml($viewModel->getBingSiteVerification()) ?>" />
<!-- END BING SITE VERIFICATION -->
<?php endif; ?>
